### ISSUE TITLE
Calibration problem: octoprint.server.api.settings - ERROR - Could not save settings for plugin OctoPrint Nanny (0.4.2)

### ISSUE THREAD

**Issue by CTFishUSA** [bitsy-ai/octoprint-nanny-plugin#109]
- OctoPrint version: 1.5.3
- Print Nanny version: 0.4.2
- OctoPi (or other OS) version: 
0.17.0
Linux octopi 5.4.83-v8+ #1379 SMP PREEMPT Mon Dec 14 13:15:14 GMT 2020 aarch64 GNU/Linux

**Describe the bug**
Did not seem to save calibration, as I saw this error in the log.

**To Reproduce**
1. From the OctoPrint web gui
2. Click on Print Nanny tab
3. Scroll down to "Start Monitoring" and then "Show Calibration"
4. Set the calibration and click Save Calibration
5. See error in the octoprint.log

**Expected behavior**
Calibration should be saved

**Screenshots**
2021-02-01 11:11:52,868 - octoprint.plugins.octoprint_nanny - INFO - Change in frames per minute or calibration detected, applying new settings
2021-02-01 11:11:52,880 - octoprint.server.api.settings - ERROR - Could not save settings for plugin OctoPrint Nanny (0.4.2)
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/settings.py", line 1034, in _saveSettings
    plugin.on_settings_save(data["plugins"][plugin_id])
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/beeline/aiotrace.py", line 93, in inner
    return fn(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_nanny/plugins.py", line 552, in on_settings_save
    self._event_bus.fire(Events.PLUGIN_OCTOPRINT_NANNY_PREDICT_OFFLINE)
AttributeError: type object 'Events' has no attribute 'PLUGIN_OCTOPRINT_NANNY_PREDICT_OFFLINE'

**Comment by leigh-johnson** [comment]
Thank you @CTFishUSA! I'm going to rework the way calibration is saved in 0.5.0 - I'll make sure this bug gets squashed as part of that work. 

https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/107
