### ISSUE TITLE
Error during device registration

### ISSUE THREAD

**Issue by dzervas** [bitsy-ai/octoprint-nanny-plugin#33]
I'm on OctoPi 0.17.0 with OctoPrint 1.5.2, Python 3.7.3 and 0.2.0 Nanny

During the Wizard the following happened after Linking the Account:
![image](https://user-images.githubusercontent.com/1029195/104112137-bdd02f00-52f3-11eb-83c2-5ccc5bc0380a.png)

but in Nanny Web interface my printer was there:
![image](https://user-images.githubusercontent.com/1029195/104112143-cc1e4b00-52f3-11eb-8ffa-6bc16245992e.png)

`octoprint.log`

```
2021-01-10 01:18:02,323 - octoprint.plugins.octoprint_nanny - INFO - Syncing profile
2021-01-10 01:18:03,187 - octoprint - ERROR - Exception on /plugin/octoprint_nanny/registerDevice [POST]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/oprint/lib/python3.7/site-packages/beeline/aiotrace.py", line 93, in inner
    return fn(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_nanny/plugins.py", line 332, in register_device
    raise result
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_nanny/plugins.py", line 274, in _register_device
    printers = await self._sync_printer_profiles()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_nanny/plugins.py", line 173, in _sync_printer_profiles
    {"printer_profile": profile}
  File "/home/pi/oprint/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_nanny/clients/rest.py", line 300, in update_or_create_printer_profile
    request
  File "/home/pi/oprint/lib/python3.7/site-packages/print_nanny_client/api_client.py", line 193, in __call_api
    raise e
  File "/home/pi/oprint/lib/python3.7/site-packages/print_nanny_client/api_client.py", line 190, in __call_api
    _request_timeout=_request_timeout)
  File "/home/pi/oprint/lib/python3.7/site-packages/print_nanny_client/rest.py", line 233, in POST
    body=body))
  File "/home/pi/oprint/lib/python3.7/site-packages/print_nanny_client/rest.py", line 184, in request
    raise ApiException(http_resp=r)
print_nanny_client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: <CIMultiDictProxy('Content-Type': 'application/json', 'Vary': 'Accept, Accept-Language, Cookie', 'Allow': 'POST, OPTIONS', 'X-Frame-Options': 'DENY', 'Content-Length': '50', 'Content-Language': 'en', 'Strict-Transport-Security': 'max-age=60; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Referrer-Policy': 'same-origin', 'Date': 'Sun, 10 Jan 2021 01:18:02 GMT', 'Via': '1.1 google', 'Alt-Svc': 'clear')>
HTTP response body: {"volume_custom_box":["Must be a valid boolean."]}

2021-01-10 01:18:03,365 - tornado.access - ERROR - 500 POST /plugin/octoprint_nanny/registerDevice (::ffff:10.13.37.110) 5900.77ms
2021-01-10 01:18:25,083 - octoprint.plugins.octoprint_nanny.manager - WARNING - Waiting 16 seconds to initialize mqtt client, missing device registration private_key=None device_id=None gcp_root_ca=None
```

**Comment by leigh-johnson** [comment]
Thanks! This was caused by too-strict validations in `print_nanny_client` (Open API v3.1 generated client). I've relaxed these fields so they can be nullable and included an update client in 0.2.3 of the plugin. 

You can safely re-register your device in OctoPrint's settings to try this again. =)
