### ISSUE TITLE
Exceptions thrown in manager _handle_print_start

### ISSUE THREAD

**Issue by leigh-johnson** [bitsy-ai/octoprint-nanny-plugin#59]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leigh/projects/octoprint-nanny-plugin/octoprint_nanny/manager.py", line 263, in _telemetry_worker
    asyncio.ensure_future(self._telemetry_queue_send_loop())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/leigh/projects/octoprint-nanny-plugin/octoprint_nanny/manager.py", line 436, in _telemetry_queue_send_loop
    await handler_fn(**event)
TypeError: _handle_print_start() got an unexpected keyword argument 'user_id'
```

**Comment by thomasctobin** [comment]
Is this solving the install bugs we are having?

**Comment by leigh-johnson** [comment]
Hey @thomasctobin, no - this fixes a bug experienced when starting a print (after installation succeeded). 

There are a couple of installation bugs out there. Can you double-check to see if you're impacted by one of these existing issues?

* `sudo apt-get` fails during install (permission error) 
https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/53
https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/55
https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/54
* 64-bit installation fails (need more info)
https://github.com/bitsy-ai/octoprint-nanny-plugin/issues/23
